### ISSUE TITLE
How to compare two `UnionVal<Record>` for equality?

### ISSUE THREAD

**Issue by bgrosse-midokura** [twop/ts-union#3]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[✅] question about how to use this project

* **Summary**
Is there a way to compare two `UnionVal<Record>` for equality?

My scenario is: nested routes, so I want to construct some matcher functions (exact, leftside a -> b, ...) with a signature like `<Record, T = UnionVal<Record>>(a: T, b: T) => boolean`.

So far I have managed to get it done by comparing `.k` and then `.p`, but the docs say that the runtime API is not stable.

**Comment by twop** [comment]
Thanks for the question!

>  but the docs say that the runtime API is not stable.

Ironically I just wanted to experiment with a different underlying data structure ^_^

### **Deep equality**

if you want something generic like `<Record, T = UnionVal<Record>>(a: T, b: T) => boolean`, you can rely on a,b having the same **structure**. Therefore, you can check it using a generic deep equality function (aka https://lodash.com/docs#isEqual). Note that this doesn't allow you to check arguments using reference equality `===` if you need to.

### **Handwritten comparer**
If you know the exact type of unions you want to check you can write a specialized function.

```ts
const enum Tab {
  Privacy,
  Stuff
}

const Route = Union({
  Home: of(null),
  Settings: of<Tab>(),
  Movie: of<string, number>() // [name, year]
});

type Route = typeof Route.T;
```

And then write some boilerplate:
```ts

// to quickly check if this is the same case
const getRouteName = Route.match({
  Home: () => 'Home',
  Settings: () => 'Settings',
  Movie: () => 'Movie'
});

const extractArgs = <T extends any[]>(...args: T) => args;

const routeArgs = Route.match<unknown[]>({
  Home: extractArgs,
  Settings: extractArgs,
  Movie: extractArgs
});

const isSamePayload = (a: unknown[], b: unknown[]) =>
  a.length === b.length && a.reduce((eq, el, i) => eq && el === b[i], true);

const isSameRoute = (a: Route, b: Route) =>
  getRouteName(a) === getRouteName(b) &&
  isSamePayload(routeArgs(a), routeArgs(b));
```

### **Generic version**
If you need to repeat the same thing several times you can write a fancy helper functions:
```ts
// split record and union declaration
const routes = {
  Home: of(null),
  Settings: of<Tab>(),
  Movie: of<string, number>() // [name, year]
};

const Route = Union(routes);

const makeComparer = <R extends RequiredRecordType>(
  record: R,
  union: UnionObj<R>
): ((a: UnionVal<R>, b: UnionVal<R>) => boolean) => {
  const keys = Object.keys(record);

  const indexMap = keys.reduce(
    (map, key, i) => ({ ...map, [key]: () => i }),
    {} as { [_: string]: () => number }
  );

  // probably  you would want to make a shortcut with 'any' type
  const getIndex = union.match<number>(indexMap as any);

  const argsMap = keys.reduce(
    (map, key) => ({ ...map, [key]: extractArgs }),
    {} as { [_: string]: typeof extractArgs }
  );

  const getArgs = union.match<unknown[]>(argsMap as any);

  return (a, b) =>
    getIndex(a) === getIndex(b) && isSamePayload(getArgs(a), getArgs(b));
};

// usage
const isSameRoute = makeComparer(routes, Route);
```
Note that you can parametrize this function by passing your own comparer for arguments instead of relying on `===`

Hope that helps

**Comment by bgrosse-midokura** [comment]
Thank you for such a detailed answer!

### Deep equality
Yes `equals` works perfectly fine for unions, regardless of underlying structure.

### Nested routes leftward equality
Let me get into some more details, sorry for not posting the whole thing earlier.

Given some more complex nested routes, I want to match if the current route "/movies/rambo/comments/all" matches left (in other words, is a subroute of) "/movies/:id".
```typescript
const currentRoute = Route.Movie("rambo", MovieRoute.Comments(Filter.Rating(10)));
const routeSectionA = Route.Movie("rambo", null);
const routeSectionB = Route.Movie("rambo", MovieRoute.Description);
matchLeft(routeSectionA, currentRoute); // true
matchLeft(routeSectionB, currentRoute); // false
```

In the following definition, I assume that `null` is a marker for optional subroutes. This is convenient for consuming, but not very explicit.

```typescript
// top route
const Route = Union({
  Home: of(null),
  Movie: of<string, MovieRoute | null>(),
});
type Route = typeof Route.T;

// a subroute
const MovieRoute = Union({
  Description: of(null),
  Comments: of<Filter>(),
});
type MovieRoute = typeof MovieRoute.T;

// not a route, but used as parameter:
const Filter = Union({ All: of(null), Rating: of<number>() });
type Filter = typeof Filter.T;

/**
 * Match route b against a from left to right.
 * When a subroute-part of a is null, that part must not match any further "right" on b.
 */
const matchLeft = <Record, T = UnionVal<Record>>(a: T, b: T): boolean => ???,
```
`matchLeft` would need to recurse the routes and match.

I think there are several issues with my approach:  
1) `equal` is not enough, because I need to stop matching when "the end"/null of the first comparable is reached (happens in `isSamePayload` too).
2) I cannot get the `UnionObj` "constructor" to use `match` between two values, for subroutes.
3) I would also actually need an extra distinction between "route" unions and nulls (to stop matching further), and other unrelated unions (like `Filter` in my example).

Perhaps I could use something like a wrapper around a generic union, but when I tried it out I got `unknown` as inferred type for the generic's value.

The good news is that I got _something_ working: I have path-strings de/encode functions, so I can just do: 
```typescript
(a: Route, b: Route) => toPath(b).indexOf(toPath(a)) === 0;
```

So, don't worry too much about it, perhaps I got the wrong idea. Feel free to close this issue if you think all this is out of scope for this library. Thanks again for your help!

**Comment by twop** [comment]
Oh, It seems I completely misunderstood your problem :(

I think your problem is too unique to have a generic solution.

I'm also leaning towards your proposed approach:
`(a: Route, b: Route) => toPath(b).indexOf(toPath(a)) === 0;`

What is nice about it is that you can potentially even use something existing for parsing. I think react-router is using a library of some sort for route parsing.
